// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 32-bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Fri Jul  1 13:20:13 2016

7seg 7seg_inst
(
	.7segin1(7segin1_sig) ,	// input  7segin1_sig
	.7segin2(7segin2_sig) ,	// input  7segin2_sig
	.7segin3(7segin3_sig) ,	// input  7segin3_sig
	.7segin4(7segin4_sig) ,	// input  7segin4_sig
	.7segout1(7segout1_sig) ,	// output  7segout1_sig
	.7segout2(7segout2_sig) ,	// output  7segout2_sig
	.7segout3(7segout3_sig) ,	// output  7segout3_sig
	.7segout4(7segout4_sig) ,	// output  7segout4_sig
	.7segout5(7segout5_sig) ,	// output  7segout5_sig
	.7segout6(7segout6_sig) ,	// output  7segout6_sig
	.7segout7(7segout7_sig) 	// output  7segout7_sig
);

